"""db changes

Revision ID: 098e90f0e870
Revises: bd634bb7bee1
Create Date: 2026-02-27 01:56:36.993072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '098e90f0e870'
down_revision: Union[str, Sequence[str], None] = 'bd634bb7bee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organization_members_user_id_fkey'), 'organization_members', type_='foreignkey')
    op.drop_constraint(op.f('organization_members_organization_id_fkey'), 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'organization_members', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('project_members_user_id_fkey'), 'project_members', type_='foreignkey')
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_constraint(op.f('projects_organization_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('projects_organization_id_fkey'), 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('project_members_user_id_fkey'), 'project_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.create_foreign_key(op.f('organization_members_organization_id_fkey'), 'organization_members', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('organization_members_user_id_fkey'), 'organization_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
