"""empty message

Revision ID: 4ab173f88517
Revises: 5f3c0b005ccc
Create Date: 2026-01-30 19:57:13.336741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab173f88517'
down_revision: Union[str, Sequence[str], None] = '5f3c0b005ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audit_logs_actor_user_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('audit_logs_organization_id_fkey'), 'audit_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('audit_logs_organization_id_fkey'), 'audit_logs', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('audit_logs_actor_user_id_fkey'), 'audit_logs', 'users', ['actor_user_id'], ['id'])
    # ### end Alembic commands ###
