"""empty message

Revision ID: 5f3c0b005ccc
Revises: 37ce5bcc402c
Create Date: 2026-01-30 19:41:52.000795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f3c0b005ccc"
down_revision: Union[str, Sequence[str], None] = "37ce5bcc402c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_logs", "actor_user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "audit_logs", "organization_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_logs", "organization_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "audit_logs", "actor_user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
