"""added server default for uuid

Revision ID: acc5f9c0f8d2
Revises: 0adfe0ba480b
Create Date: 2026-02-19 01:40:43.841196

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "acc5f9c0f8d2"
down_revision: Union[str, Sequence[str], None] = "0adfe0ba480b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
