"""empty message

Revision ID: aebf426c90d4
Revises: 4ab173f88517
Create Date: 2026-01-30 20:48:08.136121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aebf426c90d4'
down_revision: Union[str, Sequence[str], None] = '4ab173f88517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'resource_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
