"""soft delete

Revision ID: af50e7ca8027
Revises: b4bfea01adfb
Create Date: 2026-02-11 00:13:28.681270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af50e7ca8027'
down_revision: Union[str, Sequence[str], None] = 'b4bfea01adfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('organizations', 'is_deleted')
    # ### end Alembic commands ###
