"""added auth_identities table for oauth

Revision ID: ba475f162065
Revises: af50e7ca8027
Create Date: 2026-02-19 01:03:12.853651

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ba475f162065"
down_revision: Union[str, Sequence[str], None] = "af50e7ca8027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
