"""add org token_version column in org

Revision ID: ef2aac57042b
Revises: af50e7ca8027
Create Date: 2026-02-12 20:07:46.864059

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef2aac57042b"
down_revision: Union[str, Sequence[str], None] = "af50e7ca8027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("token_version", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "token_version")
    # ### end Alembic commands ###
